name: Deploy to cPanel

on:
  push:
    branches:
      - Indevelop  # Change this if your deployment branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Change to your required version

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Deploy via SFTP
      uses: samuelmeuli/action-sftp-deploy@v2
      with:
        username: c9vp4d12fmgg      # cPanel username stored in GitHub secrets
        server: ftp.chamberoflearning.com      # cPanel server stored in GitHub secrets
        port: '21'                                # or 21 for FTP
        password: TBQKuMtr%3Md  # cPanel password stored in GitHub secrets
        local-dir: build/
        remote-dir: /home/user/public_html/Dev       # cPanel directory where your app is hosted
